theme = "onedark"

[editor]
line-number = "relative"
mouse = true
cursorline = true
color-modes = true
true-color = true
auto-pairs = true
scrolloff = 10
bufferline = "multiple"
end-of-line-diagnostics = "hint"
auto-format = true
cursorcolumn = true
shell = ["fish", "-c"]
clipboard-provider = "wayland"

[editor.auto-save]
focus-lost = true
after-delay.enable = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true

[editor.inline-diagnostics]
cursor-line = "hint"

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name", "version-control"]
right = ["diagnostics", "position", "file-type"]
separator = " │ "
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"
diagnostics = ["warning", "error"]
workspace-diagnostics = ["warning", "error"]
